[parity]
chain = "spec.json"
base_path = "node0"

[network]
port = 30300
reserved_peers = "reserved_peer"

[rpc]
disable = true

[websockets]
disable = true

[account]
password = ["node0.pwd"]

[mining]
engine_signer = "0x90980525360bc40b793aed9de167542a807a3c99"
reseal_on_txs = "none"
force_sealing = true

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"